apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          env:
            - name: KAFKA_HOST
              value: {{ required "KAFKA_HOST missing" .Values.ENV.KAFKA_HOST }}
            - name: KAFKA_TOPIC
              value: {{ required "KAFKA_TOPIC missing" .Values.ENV.KAFKA_TOPIC }}
      restartPolicy: Never
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ .Values.nodeSelector.key }}: {{ .Values.nodeSelector.value }}
      {{- end }}
  backoffLimit: 0
  activeDeadlineSeconds: 18000 # 5 Hours

